### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by pangwalla** [crabvk/bar-protonmail#5]
Getting the following error.  On arch with sway, this had been working until a few days ago, not sure what changed yet, but guessing maybe an api change.

I'll have a look at what's going on in the next day or two, I'm assuming you would take a PR if it's something simple?

> bar-protonmail auth

```
Username: [username]
Password:
Traceback (most recent call last):
  File "/usr/bin/bar-protonmail", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3.10/site-packages/bar_protonmail/__init__.py", line 34, in cli
    auth.authenticate(CACHE_DIR, SESSION_PATH)
  File "/usr/lib/python3.10/site-packages/bar_protonmail/auth.py", line 17, in authenticate
    scope = session.authenticate(username, password)
  File "/usr/lib/python3.10/site-packages/proton/api.py", line 387, in authenticate
    info_response = self.api_request("/auth/info", payload)
  File "/usr/lib/python3.10/site-packages/proton/api.py", line 219, in api_request
    if not self.__metadata.try_original_url(
  File "/usr/lib/python3.10/site-packages/proton/metadata/textfile_metadata.py", line 37, in try_original_url
    self.__get_metadata_from_file()["last_api_call_time"]
  File "/usr/lib/python3.10/site-packages/proton/metadata/textfile_metadata.py", line 82, in __get_metadata_from_file
    metadata = json.load(f)
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 106 (char 105)
```

**Comment by pangwalla** [comment]
Well, good news is that deleting my cache fixed the issue, but I should have saved it before deleting, now I can't troubleshoot the issue lol

**Comment by crabvk** [comment]
Yep. I've checked with empty cache and everything works just fine.
You might have killed the script when it was writing to the disk.
